### ISSUE TITLE
Dead ?

### ISSUE THREAD

**Issue by ghost** [biz/mdc#1]
I like the template approach for MDC. It allows maximumem reuse.
But I am guessing this project is dead ?

**Comment by james-maloney** [comment]
No, just does what I need it to do. I mostly added support for the form elements to support populating form inputs and error messages. I mostly just use the standard html tags for the rest of material. 

If you feel like adding more support for other features of material I am happy to merge pull reqs.

**Comment by james-maloney** [comment]
I committed a demo app to give you an example implementation. 

`cd $GOPATH/src/github.com/biz/mdc/_examples/demo && go build && ./demo` then navigate to [http://localhost:8888/](http://localhost:8888/)

Here is the [demo code](https://github.com/biz/mdc/blob/master/_examples/demo/main.go). 

Keep in mind I have not firmed up the API and wrote this package to satisfy the requirements I had in some of my business apps.

**Comment by ghost** [comment]
Very thoughtful. Thankyou.

I will try it out. Will close
